### ISSUE TITLE
Pre-launch tasks: checklist

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#100]
## Content

See #128

## Project management tasks

- [x] Determine what the URL will be
- [x] Register the URL (if not registered already)
- [x] Agree on launch date and timeline
- [x] Define a set of critical workflows to test site pre- and post-launch
- [x] Check hosting costs have been accounted for (over-resource on launch, reduce later)
- [ ] Write and agree upon tech steps for launch plan. The plan should literally write out what happens in the order it will happen.

## Testing tasks

See #127

## Front-end tasks

See #125

## Backend tasks

See #126

## Sysadmin tasks

See #124

**Comment by thibaudcolas** [comment]
Test plan: https://github.com/wagtail/guide/blob/main/docs/test-plans.md

**Comment by thibaudcolas** [comment]
Launch plan: #136
