### ISSUE TITLE
Sysadmin launch day tasks: checklist

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#101]
- [x] Check production domains are set in Heroku "Settings / Domains and certificates"
- [x] Check production domains caching has been configured in CloudFlare page rules
- [x] Prepare to change DNS via CloudFlare to point at Heroku backend hostnames (check understanding change to be made at launch).
- [x] Check ALLOWED_HOSTS and PRIMARY_HOST include production domain in Heroku "Settings / Config Vars"
- [x] Remove htauth from production domain (leave htauth on for herokuapp.com domain by using BASIC_AUTH_WHITELISTED_HTTP_HOSTS
- [x] Change DNS for canonical domain to point at Heroku (via CloudFlare)
- [x] Generate SSL certificates and force SSL (dependent on DNS propagation) (Cloudflare/Cloudfront)
- [ ] Check Heroku dyno memory usage vs. number of workers
- [ ] Basic HTTPS uptime monitoring
- [ ] Heroku failed request threshold alert
