### ISSUE TITLE
Sysadmin pre-launch tasks checklist

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#124]
- [x] ~~Check non-www - redirects to www~~
- [x] ~~Check the canonical domain is unchanged (if originally www, new site should be www)~~
- [x] ~~Check the TTL on the DNS is low enough for timely propagation (only if nameservers not CloudFlare)~~
- [x] Check email-related DNS records (SPF, DKIM).
- [x] Check that backups are functioning correctly and that the restore process works (Heroku)
- [x] Check file uploads are backed up (confirm AWS S3 set to versioned mode)
- [x] Check web server logs are configured and being written to (Heroku)
- [x] Check Redis maxmemory policy
- [x] Enable Cloudflare Web Application Firewall
- [x] Check the performance characteristics of the app (e.g. is memory and CPU load within bounds on Heroku metrics).
- [x] Check Heroku add-on resources for anything non-standard (e.g., there may be a service on a free plan that will need to be upgraded on launch).
- [x] Add Cloudflare or Cloudfront environment variables for front-end invalidation
- [x] If using Cloudlfare, check that Polish is enabled.
- [x] Check and ensure Sentry filters out sensitive fields (Project > Settings > Security & Privacy > Additional Sensitive Fields)
- [x] Check that tracking query parameters from any marketing tools the client is planning to use are added to those that stripped out by the worker (if using Cloudflare - STRIP_QUERYSTRING_KEYS)
- [x] Block Outlook's autodiscover requests
- [x] Is ./manage.py check --deploy running without issue? Is this command added to release phase commands?
- [x] #165

**Comment by thibaudcolas** [comment]
Moved the two remaining items to #101.

**Comment by lb-** [comment]
@thibaudcolas what does 

> Block Outlook's autodiscover requests

Mean? Is this a CloudFlare config?
