### ISSUE TITLE
Final QA general pre-launch checklist

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#127]
- [x] Check all footer links work
- [x] Test sharing of all types of pages
- [x] Check site search is working (including results looking reasonable, faceted searches working, results totals look right)
- [x] Check there are no hard-coded links to the staging URL
- [x] Confirm all test content is deleted
- [x] Test redirects
- [x] Test end-to-end all critical workflows pre- and post-launch
