### ISSUE TITLE
Content pre-launch checklist

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/guide#128]
- [x] Finalise initial launch content
- [x] Check that all test content and test user accounts are deleted
- ~~[ ] Check that all existing user accounts are using strong passwords~~
- [x] Update the title tags in the “Page title” field of the “Promote” tab as per SEO guidance for initial launch content
- [x] Update meta descriptions in the Promote tab for initial launch content
