### ISSUE TITLE
User research: survey (Jonny)

### ISSUE THREAD

**Issue by Stormheg** [wagtail/guide#283]
## Tasks

- [x] Create survey form / questions
- [x] Google Forms
- [ ] Banner on Guide site – Storm
- [ ] Copy for banner
- [x] Email or Slack to people

**Comment by activus-d** [comment]
I have created a [Google form with the survey questions](I have created a Google form with the survey questions).
