### ISSUE TITLE
Style guide research

### ISSUE THREAD

**Issue by activus-d** [wagtail/guide#284]
## Task

- [x] Finish researching styleguides
- [x] Publish top 2 on https://github.com/wagtail/guide/discussions/282
- [ ] Mentors / core team decision by Wed evening

**Comment by activus-d** [comment]
I have published the [top two Writing style guide](https://github.com/wagtail/guide/discussions/282).

**Comment by activus-d** [comment]
It was unanimously agreed that the Google developer documentation style guide should be adopted. However, there is still no definite decision as regards whether American or British spelling should be used.

**Comment by thibaudcolas** [comment]
Discussed today – happy with this, though some concern we’re using different spelling between docs and Wagtail itself. Perhaps worth considering changing Wagtail to American spelling?
